### ISSUE TITLE
Errror when using with Yarn PnP

### ISSUE THREAD

**Issue by cipivanov** [abhinaba-ghosh/axe-playwright#19]
I'm trying to add the library to my app, which uses [Yarn's PnP](https://yarnpkg.com/features/pnp).

Since in a Yarn PnP setup `yarn install` does not generate a `node_modules` I get the following error:

```
    ENOENT: no such file or directory, open 'node_modules/axe-core/axe.min.js'

      17546 | 
      17547 |   openSync(p, flags, mode) {
    > 17548 |     return this.realFs.openSync(npath.fromPortablePath(p), flags, mode);
            |                        ^
      17549 |   }
      17550 | 
      17551 |   async opendirPromise(p, opts) {

      at NodeFS.openSync (.pnp.js:17548:24)
      at makeCallSync.subPath.subPath (.pnp.js:20015:26)
      at ZipOpenFS.makeCallSync (.pnp.js:20779:26)
      at ZipOpenFS.openSync (.pnp.js:20014:17)
      at VirtualFS.openSync (.pnp.js:17954:24)
      at PosixFS.openSync (.pnp.js:17954:24)
      at NodeFS.readFileSync (.pnp.js:17858:24)
      at makeCallSync.subPath.subPath (.pnp.js:20645:30)
```

I've attempted tackling the fix for this in: https://github.com/abhinaba-ghosh/axe-playwright/pull/20

**Comment by abhinaba-ghosh** [comment]
Hi @cipivanov your fix is available in `v1.1.6`.
